version: '3.3'

services: 

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
      - "27017:27017"
    volumes:
      - ./workspace:/workspace
      - type: volume
        source: mongodb_data_volume
        target: /data/db
        
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: veryHardPassword
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:mongoadmin@localhost:27017/
    depends_on:
      - mongodb

  redis-rate-limit:
    image: redis
    container_name: redis-rate-limit
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  posts-api:
    container_name: posts-api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
    - .env.local
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis-rate-limit

volumes:
  mongodb_data_volume:
    driver: local 
  redis:
    driver: local