apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: posts-hpa
  namespace: posts
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: posts
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
