apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream : "true"
  labels:
    app: posts
    version: v1
    stack: echo
    interface: rest-api
    language: TypeScript
  name: posts
  namespace: posts
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: posts
