apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-posts
config:
  client_id: "kong"
  client_secret: "ePM9uDlLCyZSQChuOz3vqC91ObP95cvA"
  discovery: "http://keycloak.iam/realms/posts/.well-known/openid-configuration"
  introspection_endpoint: "http://keycloak.iam/realms/posts/protocol/openid-connect/token/introspect"
  bearer_only: "yes"
  bearer_jwt_auth_enable: "yes"
  bearer_jwt_auth_allowed_auds:
    - account
plugin: oidc
