name: Build

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'  
      - run: npm ci
      - run: npm test --  --detectOpenHandles
      - run: npm run test:cov -- --detectOpenHandles

  build:   
    runs-on: ubuntu-latest
    needs: [test]
    env:
      DOCKER_REPOSITORY: richiebono
      IMAGE_NAME: users
      IMAGE_TAG: ${{github.run_number}}
      WORKING_DIRECTORY: users   

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: QEMU
      uses: docker/setup-qemu-action@v1

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKER_REPOSITORY }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker Image ${{ env.IMAGE_NAME }}
      run: docker build -t ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -t ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest .
      
    - name: Push Docker Image ${{ env.IMAGE_NAME }}
      run: docker push ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}
    
    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'
